version: '0.1'

services:
  url-shortener:
    image: url-shortener
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    expose:
      - 8000
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
    expose:
      - 3306
  nginx:
    image: nginx #:stable-alpine3.19
    restart: always
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - SERVER_DOMAIN=localhost
      - URLSHORTENER_SERVER=url-shortener:8000
      - NGINX_PORT=80
    ports:
      - 80:80
      - 443:443