version: '0.1'

services:
  url-shortener:
    image: url-shortener
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
    expose:
      - 3306