version: '0.2'
name: url-shortener

services:
  backend:
    image: url-shortener
    restart: always
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    environment:
      DB_USER: root
      DB_PASSWORD: ${MYSQL_PASSWORD:-password}
    depends_on:
      - db
    expose:
      - 8000
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: url_shortener
    expose:
      - 3306
  nginx:
    image: nginx:stable-alpine3.19
    restart: always
    volumes:
      - ./nginx-templates:/etc/nginx/templates
    environment:
      - PROXY_HOST=localhost
      - BACKEND_HOST=backend:8000
    depends_on:
      - backend
    expose:
      - 80

networks:
  default:
    name: ${GATEWAY_NETWORK:-bridge}
    external: true
