host: ${DB_HOST}
port: ${DB_PORT}
user: ${DB_USER}
password: ${DB_PASSWORD}
database: "url_shortener"
driver: "mysql"
maxIdleConns: 1000
maxOpenConns: 1000
connMaxIdleTime: 5
connMaxLifeTime: 0
